[package]
name = "encryptfile"
version = "0.1.0"
authors = ["John Quigley <jmquigs@gmail.com>"]

[dependencies]
rust-crypto = "^0.2.34"
rand = "^0.3.12"
byteorder = "^0.4"
#clippy = "*"

[dev-dependencies]
tempdir = "^0.3.4"
